#!/usr/bin/env lua

--[[
Sketchybar Docs: https://felixkratz.github.io/SketchyBar/
Sketchybar Lua Plugin: https://github.com/FelixKratz/SbarLua
Sketchybar App Icons: https://github.com/kvndrsslr/sketchybar-app-font/releases
Sketchybar System Stats: https://github.com/joncrangle/sketchybar-system-stats
Nerd Font Icons: https://www.nerdfonts.com/cheat-sheet
--]]

-- Install the sketchybar module if it is not already installed
os.execute("[ ! -d $HOME/.local/share/sketchybar_lua/ ] && (git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install && rm -rf /tmp/SbarLua/)")

-- Add the sketchybar module to the package cpath
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

-- Import the sketchybar module
sbar = require("sketchybar")

-- Bundle the entire initial configuration into a single message to sketchybar
sbar.begin_config()
require("init")
sbar.hotload(true)
sbar.end_config()

-- Enable callback functions executed in the lua module
sbar.event_loop()
